version: '3.8'

services:
  qgis:
    build:
      context: ./build/qgis
      dockerfile: Dockerfile
      args:
        - QGIS_USER_UID
        - QGIS_USER_GID
    container_name: ${PROJECT_NAME}-qgis-xpra
    restart: unless-stopped
    environment:
      - QGIS_USER_UID=${QGIS_USER_UID}
      - QGIS_USER_GID=${QGIS_USER_GID}
      - XPRA_PASSWORD=${XPRA_PASSWORD}
      - QGIS_DATA_DIR=${QGIS_DATA_DIR}  
      - XPRA_PORT=14500
    volumes:
      - ./data/storage:${QGIS_DATA_DIR}
      - ./config/qgis:/etc/xpra  
      - ./logs/qgis-xpra:/var/log
    tmpfs:
      - /run:uid=${QGIS_USER_UID},gid=${QGIS_USER_GID},mode=700
      - /tmp
    user: "${QGIS_USER_UID}:${QGIS_USER_GID}"
    ports:
      - "${XPRA_PORT}:14500"
    tty: true      
    networks:
      - qgis-network

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}-nginx-proxy
    restart: unless-stopped
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
      - ${PWD}/nginx/ssl:/etc/nginx/ssl:ro
      - ${PWD}/nginx/ssl:/etc/nginx/ssl:ro
      - ${PWD}/nginx/ssl:/etc/nginx/ssl:ro
      - ${PWD}/data/certbot/conf:/etc/letsencrypt # Mount Certbot data
      - ${PWD}/data/certbot/www:/var/www/certbot # Mount Certbot webroot
    ports:
      - "${NGINX_PORT}:443"
      - "80:80"
      - "${NGINX_HTTPS_PORT}:443" # Add HTTPS port
    depends_on:
      - qgis
      - filebrowser
    networks:
      - qgis-network

  filebrowser:
    image: filebrowser/filebrowser
    container_name: ${PROJECT_NAME}-filebrowser
    restart: unless-stopped
    environment:
      - FB_BASEURL=${FILEBROWSER_BASE_URL}
      - FB_DATABASE=/config/db/database.db
    volumes:
      - ./data/storage:/srv
      - ./config/filebrowser/filebrowser.json:/.filebrowser.json
      - ./config/filebrowser/db:/config/db
      - ./logs/filebrowser:/logs
    user: "${QGIS_USER_UID}:${QGIS_USER_GID}"
    ports: 
      - "8080:80"
    networks:
      - qgis-network

  certbot-fqdn:
    image: certbot/certbot:latest
    container_name: ${PROJECT_NAME}-certbot-fqdn
    volumes:
      - ${PWD}/data/certbot/conf:/etc/letsencrypt
      - ${PWD}/data/certbot/www:/var/www/certbot
      - ./logs/certbot-fqdn:/var/www/letsencript
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${DOMAIN_NAME}
    networks:
      - qgis-network

  certbot-duckdns:
    image: certbot/certbot:latest
    container_name: ${PROJECT_NAME}-certbot-duckdns
    volumes:
      - ${PWD}/data/certbot/conf:/etc/letsencrypt
      - ${PWD}/certbot:/etc/certbot
      - ./logs/certbot-duckdns:/var/log/letsencrypt
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --manual-public-ip-logging-ok --manual-auth-hook \"./certbot/duckdns.sh renew\" --manual-cleanup-hook \"./certbot/duckdns.sh cleanup\" --deploy-hook \"docker exec -it ${PROJECT_NAME}-nginx-proxy nginx -s reload\" -d ${DUCKDNS_DOMAIN} || exit 1; sleep 12h & wait $${!}; done;'"
    networks:
      - qgis-network

  self-signed-cert:
    image: paulczar/omgwtfssl
    container_name: ${PROJECT_NAME}-self-signed-cert
    environment:
      - SSL_SUBJECT="example.com"
    volumes:
      - ${PWD}/data/certbot/conf:/certs
      - ./logs/self-signed-cert:/var/log        
    networks:
      - qgis-network

volumes:
  data:

networks:
  qgis-network:
    driver: bridge
